[defaults]
checkout_dir = "~/Projects/references"
checkout_dir_windows = "/d/Projects/references"
depth = 1

[source.baoyu-skills]

[source.baoyu-skills.remote]
url = "https://github.com/JimLiu/baoyu-skills.git"

[source.frontend-slides]

[source.frontend-slides.remote]
url = "https://github.com/zarazhangrui/frontend-slides.git"

[source.guizang-ppt-skill]

[source.guizang-ppt-skill.remote]
url = "https://github.com/op7418/guizang-ppt-skill.git"

[source.Waza]

[source.Waza.remote]
url = "https://github.com/tw93/Waza.git"

[source.awesome-copilot]

[source.awesome-copilot.remote]
url = "https://github.com/github/awesome-copilot"

[source.superpowers]

[source.superpowers.remote]
url = "https://github.com/obra/superpowers"

[source.skills]

[source.skills.remote]
url = "https://github.com/anthropics/skills"

[source."mattpocock/skills"]

[source."mattpocock/skills".remote]
url = "https://github.com/mattpocock/skills.git"

[source.ljg-skills]

[source.ljg-skills.remote]
url = "https://github.com/lijigang/ljg-skills"
ref = "md"

[source.archify]

[source.archify.remote]
url = "https://github.com/tt-a1i/archify"

[source.claude-plugins-official]

[source.claude-plugins-official.remote]
url = "https://github.com/anthropics/claude-plugins-official"

[source.ELI5]

[source.ELI5.remote]
url = "https://github.com/DreambigOu/ELI5.git"

[source.reclaim-code-entropy]

[source.reclaim-code-entropy.remote]
url = "https://github.com/Yevanchen/reclaim-code-entropy.git"
